server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Auth Service (Public + Private)
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        
        # Order Service (Protected)
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Driver Service (Protected)
        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
          filters:
            - name: JwtAuthenticationFilter

        # Tracking Service (Protected)
        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/api/v1/tracking/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Websocket (Public/Protected handled in app)
        - id: tracking-ws
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/ws/**

        # PoD Service (Protected)
        - id: pod-service
          uri: lb://POD-SERVICE
          predicates:
            - Path=/api/v1/pod/**
          filters:
            - name: JwtAuthenticationFilter

jwt:
  # Must match Auth Service Secret
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
